
import 'package:loh_ecommerce_app/models/list_item.dart';

import '../utils/resources/app_images.dart';

Map<String, List<ListItem>> tabItems = {
  "All": [
    ListItem("Shoe 1", AppImage.shoeOne, "popular", "new", "high", "high"),
    ListItem("Shoe 2", AppImage.shoeTwo, "not-popular", "new", "low", "high"),
    ListItem("Gloves 1", AppImage.gloves, "popular", "new", "high", "high"),
    ListItem("Shoe 3", AppImage.shoeThree, "popular", "new", "low", "low"),
    ListItem("Belts 1", AppImage.belt, "popular", "new", "high", "high"),
    ListItem("Belts 2", AppImage.belt, "not-popular", "new", "low", "high"),
    ListItem("Belts 3", AppImage.belt, "popular", "new", "low", "low"),
    ListItem("Gloves 2", AppImage.gloves, "not-popular", "new", "low", "high"),
    ListItem("Gloves 3", AppImage.gloves, "popular", "new", "low", "low"),
    ListItem("Shoe 4", AppImage.shoeFour, "not-popular", "new", "high", "high"),
    ListItem("Shoe 5", AppImage.shoeFive, "not-popular", "not-new", "high", "low"),
    ListItem("Shoe 6", AppImage.shoeSix, "popular", "new", "high", "high"),
    ListItem("Shoe 7", AppImage.shoeSeven, "popular", "not-new", "high", "high"),
    ListItem("Shoe 8", AppImage.shoeEight, "not-popular", "new", "high", "low"),
    ListItem("Shoe 9", AppImage.shoeNine, "not-popular", "new", "high", "high"),
    ListItem("Shoe 10", AppImage.shoeTen, "popular", "not-new", "high", "high"),
    ListItem("Belts 1", AppImage.belt, "popular", "new", "high", "high"),
    ListItem("Belts 2", AppImage.belt, "not-popular", "new", "low", "high"),
    ListItem("Belts 3", AppImage.belt, "popular", "new", "low", "low"),
    ListItem("Belts 4", AppImage.belt, "not-popular", "new", "high", "high"),
    ListItem("Belts 5", AppImage.belt, "not-popular", "not-new", "high", "low"),
    ListItem("Belts 6", AppImage.belt, "popular", "new", "high", "high"),
    ListItem("Belts 7", AppImage.belt, "popular", "not-new", "high", "high"),
    ListItem("Belts 8", AppImage.belt, "not-popular", "new", "high", "low"),
    ListItem("Belts 9", AppImage.belt, "not-popular", "new", "high", "high"),
    ListItem("Belts 10", AppImage.belt, "popular", "not-new", "high", "high"),
    ListItem("Gloves 1", AppImage.gloves, "popular", "new", "high", "high"),
    ListItem("Gloves 2", AppImage.gloves, "not-popular", "new", "low", "high"),
    ListItem("Gloves 3", AppImage.gloves, "popular", "new", "low", "low"),
    ListItem("Gloves 4", AppImage.gloves, "not-popular", "new", "high", "high"),
    ListItem("Gloves 5", AppImage.gloves, "not-popular", "not-new", "high", "low"),
    ListItem("Gloves 6", AppImage.gloves, "popular", "new", "high", "high"),
    ListItem("Gloves 7", AppImage.gloves, "popular", "not-new", "high", "high"),
    ListItem("Gloves 8", AppImage.gloves, "not-popular", "new", "high", "low"),
    ListItem("Gloves 9", AppImage.gloves, "not-popular", "new", "high", "high"),
    ListItem("Gloves 10", AppImage.gloves, "popular", "not-new", "high", "high"),
  ],
  "Shoes": [
    ListItem("Shoe 1", AppImage.shoeOne, "popular", "new", "high", "high"),
    ListItem("Shoe 2", AppImage.shoeTwo, "not-popular", "new", "low", "high"),
    ListItem("Shoe 3", AppImage.shoeThree, "popular", "new", "low", "low"),
    ListItem("Shoe 4", AppImage.shoeFour, "not-popular", "new", "high", "high"),
    ListItem("Shoe 5", AppImage.shoeFive, "not-popular", "not-new", "high", "low"),
    ListItem("Shoe 6", AppImage.shoeSix, "popular", "new", "high", "high"),
    ListItem("Shoe 7", AppImage.shoeSeven, "popular", "not-new", "high", "high"),
    ListItem("Shoe 8", AppImage.shoeEight, "not-popular", "new", "high", "low"),
    ListItem("Shoe 9", AppImage.shoeNine, "not-popular", "new", "high", "high"),
    ListItem("Shoe 10", AppImage.shoeTen, "popular", "not-new", "high", "high"),
    ListItem("Shoe 1", AppImage.shoeOne, "popular", "new", "high", "high"),
    ListItem("Shoe 2", AppImage.shoeTwo, "not-popular", "new", "low", "high"),
    ListItem("Shoe 3", AppImage.shoeThree, "popular", "new", "low", "low"),
    ListItem("Shoe 4", AppImage.shoeFour, "not-popular", "new", "high", "high"),
    ListItem("Shoe 5", AppImage.shoeFive, "not-popular", "not-new", "high", "low"),
    ListItem("Shoe 6", AppImage.shoeSix, "popular", "new", "high", "high"),
    ListItem("Shoe 7", AppImage.shoeSeven, "popular", "not-new", "high", "high"),
    ListItem("Shoe 8", AppImage.shoeEight, "not-popular", "new", "high", "low"),
    ListItem("Shoe 9", AppImage.shoeNine, "not-popular", "new", "high", "high"),
    ListItem("Shoe 10", AppImage.shoeTen, "popular", "not-new", "high", "high"),
  ],
  "Belts": [
    ListItem("Belts 1", AppImage.belt, "popular", "new", "high", "high"),
    ListItem("Belts 2", AppImage.belt, "not-popular", "new", "low", "high"),
    ListItem("Belts 3", AppImage.belt, "popular", "new", "low", "low"),
    ListItem("Belts 4", AppImage.belt, "not-popular", "new", "high", "high"),
    ListItem("Belts 5", AppImage.belt, "not-popular", "not-new", "high", "low"),
    ListItem("Belts 6", AppImage.belt, "popular", "new", "high", "high"),
    ListItem("Belts 7", AppImage.belt, "popular", "not-new", "high", "high"),
    ListItem("Belts 8", AppImage.belt, "not-popular", "new", "high", "low"),
    ListItem("Belts 9", AppImage.belt, "not-popular", "new", "high", "high"),
    ListItem("Belts 10", AppImage.belt, "popular", "not-new", "high", "high"),
    ListItem("Belts 1", AppImage.belt, "popular", "new", "high", "high"),
    ListItem("Belts 2", AppImage.belt, "not-popular", "new", "low", "high"),
    ListItem("Belts 3", AppImage.belt, "popular", "new", "low", "low"),
    ListItem("Belts 4", AppImage.belt, "not-popular", "new", "high", "high"),
    ListItem("Belts 5", AppImage.belt, "not-popular", "not-new", "high", "low"),
    ListItem("Belts 6", AppImage.belt, "popular", "new", "high", "high"),
    ListItem("Belts 7", AppImage.belt, "popular", "not-new", "high", "high"),
    ListItem("Belts 8", AppImage.belt, "not-popular", "new", "high", "low"),
    ListItem("Belts 9", AppImage.belt, "not-popular", "new", "high", "high"),
    ListItem("Belts 10", AppImage.belt, "popular", "not-new", "high", "high"),
  ],
  "Gloves": [
    ListItem("Gloves 1", AppImage.gloves, "popular", "new", "high", "high"),
    ListItem("Gloves 2", AppImage.gloves, "not-popular", "new", "low", "high"),
    ListItem("Gloves 3", AppImage.gloves, "popular", "new", "low", "low"),
    ListItem("Gloves 4", AppImage.gloves, "not-popular", "new", "high", "high"),
    ListItem("Gloves 5", AppImage.gloves, "not-popular", "not-new", "high", "low"),
    ListItem("Gloves 6", AppImage.gloves, "popular", "new", "high", "high"),
    ListItem("Gloves 7", AppImage.gloves, "popular", "not-new", "high", "high"),
    ListItem("Gloves 8", AppImage.gloves, "not-popular", "new", "high", "low"),
    ListItem("Gloves 9", AppImage.gloves, "not-popular", "new", "high", "high"),
    ListItem("Gloves 10", AppImage.gloves, "popular", "not-new", "high", "high"),
    ListItem("Gloves 1", AppImage.gloves, "popular", "new", "high", "high"),
    ListItem("Gloves 2", AppImage.gloves, "not-popular", "new", "low", "high"),
    ListItem("Gloves 3", AppImage.gloves, "popular", "new", "low", "low"),
    ListItem("Gloves 4", AppImage.gloves, "not-popular", "new", "high", "high"),
    ListItem("Gloves 5", AppImage.gloves, "not-popular", "not-new", "high", "low"),
    ListItem("Gloves 6", AppImage.gloves, "popular", "new", "high", "high"),
    ListItem("Gloves 7", AppImage.gloves, "popular", "not-new", "high", "high"),
    ListItem("Gloves 8", AppImage.gloves, "not-popular", "new", "high", "low"),
    ListItem("Gloves 9", AppImage.gloves, "not-popular", "new", "high", "high"),
    ListItem("Gloves 10", AppImage.gloves, "popular", "not-new", "high", "high"),
  ],

};
